! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The ODE Function of Chemical Model File
! 
! Generated by KPP-3.3.0 symbolic chemistry Kinetics PreProcessor
!       (https:/github.com/KineticPreProcessor/KPP
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian,   Villanova University, Philadelphia, PA, USA
!        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
!        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
!        H. Lin,      Harvard University, Cambridge, MA, USA
!        R. Yantosca, Harvard University, Cambridge, MA, USA
! 
! File                 : cloudchem_Function.F90
! Equation file        : cloudchem.kpp
! Output root filename : cloudchem
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE cloudchem_Function

  USE cloudchem_Parameters
  IMPLICIT NONE

! A - Rate for each equation
  REAL(kind=dp) :: A(NREACT)
  !$OMP THREADPRIVATE(  A )

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Fun - time derivatives of variables - Aggregate form
!   Arguments :
!      V         - Concentrations of variable species (local)
!      F         - Concentrations of fixed species (local)
!      RCT       - Rate constants (local)
!      Vdot      - Time derivative of variable species concentrations
!      Aout      - Optional argument to return equation rate constants
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Fun ( V, F, RCT, Vdot, Aout )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! F - Concentrations of fixed species (local)
  REAL(kind=dp) :: F(NFIX)
! RCT - Rate constants (local)
  REAL(kind=dp) :: RCT(NREACT)
! Vdot - Time derivative of variable species concentrations
  REAL(kind=dp) :: Vdot(NVAR)
! Aout - Optional argument to return equation rate constants
  REAL(kind=dp), OPTIONAL :: Aout(NREACT)


! Computation of equation rates
  A(1) = RCT(1)*V(13)*V(34)
  A(2) = RCT(2)*V(29)*V(35)
  A(3) = RCT(3)*V(29)*V(31)
  A(4) = 1e-12*V(29)*V(30)
  A(5) = 1e-12*V(29)*V(29)
  A(6) = 1.54e-10*V(19)*V(34)
  A(7) = RCT(7)*V(27)
  A(8) = RCT(8)*V(27)*V(35)
  A(9) = RCT(9)*V(27)*V(31)
  A(10) = 1e-12*V(27)*V(30)
  A(11) = 2.17e-11*V(14)*V(34)
  A(12) = RCT(12)*V(33)*V(35)
  A(13) = RCT(13)*V(31)*V(33)
  A(14) = 1e-12*V(30)*V(33)
  A(15) = 8.4e-12*V(12)*V(34)
  A(16) = 8.4e-12*V(10)*V(34)
  A(17) = RCT(17)*V(20)*V(34)
  A(18) = RCT(18)*V(28)*V(32)
  A(19) = RCT(19)*V(11)
  A(20) = RCT(20)*V(28)*V(31)
  A(21) = 1.63e-12*V(22)*V(34)
  A(22) = RCT(22)*V(16)*V(34)
  A(23) = RCT(23)*V(24)*V(34)
  A(24) = RCT(24)*V(17)*V(34)
  A(25) = RCT(25)*V(18)*V(34)
  A(26) = RCT(26)*V(25)*V(31)
  A(27) = RCT(27)*V(25)*V(34)
  A(28) = RCT(28)*V(25)*V(35)
  A(29) = RCT(29)*V(31)*V(35)
  A(30) = RCT(30)*V(32)*V(34)
  A(31) = RCT(31)*V(9)*V(34)
  A(32) = RCT(32)*V(26)*V(31)
  A(33) = RCT(33)*V(32)*V(35)
  A(34) = RCT(34)*V(15)*V(34)
  A(35) = RCT(35)*V(34)*V(35)
  A(36) = RCT(36)*V(23)*V(34)
  A(37) = RCT(37)*V(35)*V(35)
  A(38) = RCT(38)*V(21)*V(34)
  A(39) = RCT(39)*V(8)*V(34)
  A(40) = RCT(40)*V(30)*V(35)
  A(41) = RCT(41)*V(30)*V(31)
  A(42) = RCT(42)*V(15)
  A(43) = RCT(43)*V(13)*V(26)
  A(44) = RCT(44)*V(25)*V(32)
  A(45) = RCT(45)*V(25)
  A(46) = RCT(46)*V(7)
  A(47) = RCT(47)*V(1)
  A(48) = RCT(48)*V(23)
  A(49) = RCT(49)*V(32)
  A(50) = RCT(50)*V(26)
  A(51) = RCT(51)*V(19)

  !### Use Aout to return equation rates
  IF ( PRESENT( Aout ) ) Aout = A

! Aggregate function
  Vdot(1) = -A(47)
  Vdot(2) = A(40)
  Vdot(3) = 0.3*A(4)
  Vdot(4) = A(12)
  Vdot(5) = 0.3*A(14)
  Vdot(6) = A(35)
  Vdot(7) = A(37)-A(46)
  Vdot(8) = -A(39)
  Vdot(9) = A(30)-A(31)
  Vdot(10) = A(7)-A(16)
  Vdot(11) = A(18)-A(19)
  Vdot(12) = 0.7*A(6)-A(15)
  Vdot(13) = -A(1)-A(43)
  Vdot(14) = 0.105*A(3)-A(11)+A(43)
  Vdot(15) = A(33)-A(34)-A(42)
  Vdot(16) = A(8)-A(22)
  Vdot(17) = 0.13*A(9)-A(24)
  Vdot(18) = 0.3*A(10)-A(25)
  Vdot(19) = A(2)-A(6)-A(51)
  Vdot(20) = 0.896*A(3)+0.7*A(4)+2*A(5)+0.87*A(9)+0.7*A(10)+A(15)+A(16)-A(17)+A(22)+A(25)
  Vdot(21) = 2*A(5)+1.86*A(20)+2*A(23)+A(36)-A(38)+A(48)
  Vdot(22) = 0.16*A(13)-A(21)
  Vdot(23) = 0.896*A(3)+0.87*A(9)+0.7*A(10)+0.84*A(13)+0.7*A(14)+A(15)+A(16)+1.86*A(20)+A(21)+A(22)+2*A(23)+A(24)+A(25)&
               &-A(36)+A(41)-A(48)+A(51)
  Vdot(24) = 0.84*A(13)+0.7*A(14)+0.07*A(20)+A(21)-A(23)+A(24)
  Vdot(25) = -A(26)-A(27)-A(28)-A(44)-A(45)+A(49)
  Vdot(26) = A(31)-A(32)-A(43)+A(44)-A(50)
  Vdot(27) = 0.3*A(6)-A(7)-A(8)-A(9)-A(10)
  Vdot(28) = A(17)-A(18)-A(20)
  Vdot(29) = A(1)-A(2)-A(3)-A(4)-2*A(5)
  Vdot(30) = -A(4)-A(10)-A(14)+A(19)+A(39)-A(40)-A(41)
  Vdot(31) = -A(3)-A(9)-A(13)-A(20)-A(26)-A(29)-A(32)-A(41)+A(49)
  Vdot(32) = 0.896*A(3)+0.87*A(9)+0.84*A(13)-A(18)+A(19)+0.93*A(20)+A(21)+A(23)+A(26)+A(29)-A(30)+2*A(32)-A(33)+A(34)&
               &+A(41)+A(42)-A(44)-A(49)+A(50)
  Vdot(33) = A(11)-A(12)-A(13)-A(14)
  Vdot(34) = -A(1)-0.3*A(6)+A(7)-A(11)-A(15)-A(17)-A(21)-A(22)-A(23)-A(24)-A(25)-A(27)+A(28)+A(29)-A(30)-A(31)-A(34)&
               &-A(35)-A(36)-A(38)-A(39)+2*A(45)+2*A(46)+A(47)+2*A(51)
  Vdot(35) = -A(2)+0.896*A(3)+0.4*A(4)+2*A(5)-A(8)-A(12)+0.93*A(20)+A(21)+A(23)+A(27)-A(28)-A(29)-A(33)-A(35)+A(36)-2&
               &*A(37)+A(38)-A(40)+A(42)+2*A(48)
      
END SUBROUTINE Fun

! End of Fun function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Fun_SPLIT - time derivatives of variables - Split form
!   Arguments :
!      V         - Concentrations of variable species (local)
!      F         - Concentrations of fixed species (local)
!      RCT       - Rate constants (local)
!      Vdot      - Time derivative of variable species concentrations
!      P_VAR     - Production term
!      D_VAR     - Destruction term
!      Aout      - Optional argument to return equation rate constants
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Fun_SPLIT ( V, F, RCT, Vdot, P_VAR, D_VAR, Aout )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! F - Concentrations of fixed species (local)
  REAL(kind=dp) :: F(NFIX)
! RCT - Rate constants (local)
  REAL(kind=dp) :: RCT(NREACT)
! Vdot - Time derivative of variable species concentrations
  REAL(kind=dp) :: Vdot(NVAR)
! P_VAR - Production term
  REAL(kind=dp) :: P_VAR(NVAR)
! D_VAR - Destruction term
  REAL(kind=dp) :: D_VAR(NVAR)
! Aout - Optional argument to return equation rate constants
  REAL(kind=dp), OPTIONAL :: Aout(NREACT)


! Computation of equation rates
  A(1) = RCT(1)*V(13)*V(34)
  A(2) = RCT(2)*V(29)*V(35)
  A(3) = RCT(3)*V(29)*V(31)
  A(4) = 1e-12*V(29)*V(30)
  A(5) = 1e-12*V(29)*V(29)
  A(6) = 1.54e-10*V(19)*V(34)
  A(7) = RCT(7)*V(27)
  A(8) = RCT(8)*V(27)*V(35)
  A(9) = RCT(9)*V(27)*V(31)
  A(10) = 1e-12*V(27)*V(30)
  A(11) = 2.17e-11*V(14)*V(34)
  A(12) = RCT(12)*V(33)*V(35)
  A(13) = RCT(13)*V(31)*V(33)
  A(14) = 1e-12*V(30)*V(33)
  A(15) = 8.4e-12*V(12)*V(34)
  A(16) = 8.4e-12*V(10)*V(34)
  A(17) = RCT(17)*V(20)*V(34)
  A(18) = RCT(18)*V(28)*V(32)
  A(19) = RCT(19)*V(11)
  A(20) = RCT(20)*V(28)*V(31)
  A(21) = 1.63e-12*V(22)*V(34)
  A(22) = RCT(22)*V(16)*V(34)
  A(23) = RCT(23)*V(24)*V(34)
  A(24) = RCT(24)*V(17)*V(34)
  A(25) = RCT(25)*V(18)*V(34)
  A(26) = RCT(26)*V(25)*V(31)
  A(27) = RCT(27)*V(25)*V(34)
  A(28) = RCT(28)*V(25)*V(35)
  A(29) = RCT(29)*V(31)*V(35)
  A(30) = RCT(30)*V(32)*V(34)
  A(31) = RCT(31)*V(9)*V(34)
  A(32) = RCT(32)*V(26)*V(31)
  A(33) = RCT(33)*V(32)*V(35)
  A(34) = RCT(34)*V(15)*V(34)
  A(35) = RCT(35)*V(34)*V(35)
  A(36) = RCT(36)*V(23)*V(34)
  A(37) = RCT(37)*V(35)*V(35)
  A(38) = RCT(38)*V(21)*V(34)
  A(39) = RCT(39)*V(8)*V(34)
  A(40) = RCT(40)*V(30)*V(35)
  A(41) = RCT(41)*V(30)*V(31)
  A(42) = RCT(42)*V(15)
  A(43) = RCT(43)*V(13)*V(26)
  A(44) = RCT(44)*V(25)*V(32)
  A(45) = RCT(45)*V(25)
  A(46) = RCT(46)*V(7)
  A(47) = RCT(47)*V(1)
  A(48) = RCT(48)*V(23)
  A(49) = RCT(49)*V(32)
  A(50) = RCT(50)*V(26)
  A(51) = RCT(51)*V(19)

  !### Use Aout to return equation rates
  IF ( PRESENT( Aout ) ) Aout = A

! Production function
  P_VAR(1) = 0
  P_VAR(2) = A(40)
  P_VAR(3) = 0.3*A(4)
  P_VAR(4) = A(12)
  P_VAR(5) = 0.3*A(14)
  P_VAR(6) = A(35)
  P_VAR(7) = A(37)
  P_VAR(8) = 0
  P_VAR(9) = A(30)
  P_VAR(10) = A(7)
  P_VAR(11) = A(18)
  P_VAR(12) = 0.7*A(6)
  P_VAR(13) = 0
  P_VAR(14) = 0.105*A(3)+A(43)
  P_VAR(15) = A(33)
  P_VAR(16) = A(8)
  P_VAR(17) = 0.13*A(9)
  P_VAR(18) = 0.3*A(10)
  P_VAR(19) = A(2)
  P_VAR(20) = 0.896*A(3)+0.7*A(4)+2*A(5)+0.87*A(9)+0.7*A(10)+A(15)+A(16)+A(22)+A(25)
  P_VAR(21) = 2*A(5)+1.86*A(20)+2*A(23)+A(36)+A(48)
  P_VAR(22) = 0.16*A(13)
  P_VAR(23) = 0.896*A(3)+0.87*A(9)+0.7*A(10)+0.84*A(13)+0.7*A(14)+A(15)+A(16)+1.86*A(20)+A(21)+A(22)+2*A(23)+A(24)+A(25)&
                &+A(41)+A(51)
  P_VAR(24) = 0.84*A(13)+0.7*A(14)+0.07*A(20)+A(21)+A(24)
  P_VAR(25) = A(49)
  P_VAR(26) = A(31)+A(44)
  P_VAR(27) = 0.3*A(6)
  P_VAR(28) = A(17)
  P_VAR(29) = A(1)
  P_VAR(30) = A(19)+A(39)
  P_VAR(31) = A(49)
  P_VAR(32) = 0.896*A(3)+0.87*A(9)+0.84*A(13)+A(19)+0.93*A(20)+A(21)+A(23)+A(26)+A(29)+2*A(32)+A(34)+A(41)+A(42)+A(50)
  P_VAR(33) = A(11)
  P_VAR(34) = 0.7*A(6)+A(7)+A(16)+A(28)+A(29)+2*A(45)+2*A(46)+A(47)+2*A(51)
  P_VAR(35) = 0.896*A(3)+0.4*A(4)+2*A(5)+0.93*A(20)+A(21)+A(23)+A(27)+A(36)+A(38)+A(42)+2*A(48)

! Destruction function
  D_VAR(1) = RCT(47)
  D_VAR(2) = 0
  D_VAR(3) = 0
  D_VAR(4) = 0
  D_VAR(5) = 0
  D_VAR(6) = 0
  D_VAR(7) = RCT(46)
  D_VAR(8) = RCT(39)*V(34)
  D_VAR(9) = RCT(31)*V(34)
  D_VAR(10) = 8.4e-12*V(34)
  D_VAR(11) = RCT(19)
  D_VAR(12) = 8.4e-12*V(34)
  D_VAR(13) = RCT(1)*V(34)+RCT(43)*V(26)
  D_VAR(14) = 2.17e-11*V(34)
  D_VAR(15) = RCT(34)*V(34)+RCT(42)
  D_VAR(16) = RCT(22)*V(34)
  D_VAR(17) = RCT(24)*V(34)
  D_VAR(18) = RCT(25)*V(34)
  D_VAR(19) = 1.54e-10*V(34)+RCT(51)
  D_VAR(20) = RCT(17)*V(34)
  D_VAR(21) = RCT(38)*V(34)
  D_VAR(22) = 1.63e-12*V(34)
  D_VAR(23) = RCT(36)*V(34)+RCT(48)
  D_VAR(24) = RCT(23)*V(34)
  D_VAR(25) = RCT(26)*V(31)+RCT(27)*V(34)+RCT(28)*V(35)+RCT(44)*V(32)+RCT(45)
  D_VAR(26) = RCT(32)*V(31)+RCT(43)*V(13)+RCT(50)
  D_VAR(27) = RCT(7)+RCT(8)*V(35)+RCT(9)*V(31)+1e-12*V(30)
  D_VAR(28) = RCT(18)*V(32)+RCT(20)*V(31)
  D_VAR(29) = RCT(2)*V(35)+RCT(3)*V(31)+1e-12*V(30)+1e-12*2*V(29)
  D_VAR(30) = 1e-12*V(29)+1e-12*V(27)+1e-12*V(33)+RCT(40)*V(35)+RCT(41)*V(31)
  D_VAR(31) = RCT(3)*V(29)+RCT(9)*V(27)+RCT(13)*V(33)+RCT(20)*V(28)+RCT(26)*V(25)+RCT(29)*V(35)+RCT(32)*V(26)+RCT(41)&
                &*V(30)
  D_VAR(32) = RCT(18)*V(28)+RCT(30)*V(34)+RCT(33)*V(35)+RCT(44)*V(25)+RCT(49)
  D_VAR(33) = RCT(12)*V(35)+RCT(13)*V(31)+1e-12*V(30)
  D_VAR(34) = RCT(1)*V(13)+1.54e-10*V(19)+2.17e-11*V(14)+8.4e-12*V(12)+8.4e-12*V(10)+RCT(17)*V(20)+1.63e-12*V(22)&
                &+RCT(22)*V(16)+RCT(23)*V(24)+RCT(24)*V(17)+RCT(25)*V(18)+RCT(27)*V(25)+RCT(30)*V(32)+RCT(31)*V(9)+RCT(34)&
                &*V(15)+RCT(35)*V(35)+RCT(36)*V(23)+RCT(38)*V(21)+RCT(39)*V(8)
  D_VAR(35) = RCT(2)*V(29)+RCT(8)*V(27)+RCT(12)*V(33)+RCT(28)*V(25)+RCT(29)*V(31)+RCT(33)*V(32)+RCT(35)*V(34)+RCT(37)*2&
                &*V(35)+RCT(40)*V(30)

  Vdot = P_VAR - D_VAR*V
      
END SUBROUTINE Fun_SPLIT

! End of Fun_SPLIT function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! CalcStoichNum - calculate stoichiometric numbers
!   Arguments :
!      StoichNum - Stoichiometric numbers
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE CalcStoichNum ( StoichNum )

! StoichNum - Stoichiometric numbers
  REAL(kind=dp) :: StoichNum(NVAR,NREACT)

  StoichNum(:,:) = 0.
  StoichNum(1,47) = -1
  StoichNum(2,40) = 1
  StoichNum(3,4) = 0.3
  StoichNum(4,12) = 1
  StoichNum(5,14) = 0.3
  StoichNum(6,35) = 1
  StoichNum(7,37) = 1
  StoichNum(7,46) = -1
  StoichNum(8,39) = -1
  StoichNum(9,30) = 1
  StoichNum(9,31) = -1
  StoichNum(10,7) = 1
  StoichNum(10,16) = -1
  StoichNum(11,18) = 1
  StoichNum(11,19) = -1
  StoichNum(12,6) = 0.7
  StoichNum(12,15) = -1
  StoichNum(13,1) = -1
  StoichNum(13,43) = -1
  StoichNum(14,3) = 0.105
  StoichNum(14,11) = -1
  StoichNum(14,43) = 1
  StoichNum(15,33) = 1
  StoichNum(15,34) = -1
  StoichNum(15,42) = -1
  StoichNum(16,8) = 1
  StoichNum(16,22) = -1
  StoichNum(17,9) = 0.13
  StoichNum(17,24) = -1
  StoichNum(18,10) = 0.3
  StoichNum(18,25) = -1
  StoichNum(19,2) = 1
  StoichNum(19,6) = -1
  StoichNum(19,51) = -1
  StoichNum(20,3) = 0.896
  StoichNum(20,4) = 0.7
  StoichNum(20,5) = 2
  StoichNum(20,9) = 0.87
  StoichNum(20,10) = 0.7
  StoichNum(20,15) = 1
  StoichNum(20,16) = 1
  StoichNum(20,17) = -1
  StoichNum(20,22) = 1
  StoichNum(20,25) = 1
  StoichNum(21,5) = 2
  StoichNum(21,20) = 1.86
  StoichNum(21,23) = 2
  StoichNum(21,36) = 1
  StoichNum(21,38) = -1
  StoichNum(21,48) = 1
  StoichNum(22,13) = 0.16
  StoichNum(22,21) = -1
  StoichNum(23,3) = 0.896
  StoichNum(23,9) = 0.87
  StoichNum(23,10) = 0.7
  StoichNum(23,13) = 0.84
  StoichNum(23,14) = 0.7
  StoichNum(23,15) = 1
  StoichNum(23,16) = 1
  StoichNum(23,20) = 1.86
  StoichNum(23,21) = 1
  StoichNum(23,22) = 1
  StoichNum(23,23) = 2
  StoichNum(23,24) = 1
  StoichNum(23,25) = 1
  StoichNum(23,36) = -1
  StoichNum(23,41) = 1
  StoichNum(23,48) = -1
  StoichNum(23,51) = 1
  StoichNum(24,13) = 0.84
  StoichNum(24,14) = 0.7
  StoichNum(24,20) = 0.07
  StoichNum(24,21) = 1
  StoichNum(24,23) = -1
  StoichNum(24,24) = 1
  StoichNum(25,26) = -1
  StoichNum(25,27) = -1
  StoichNum(25,28) = -1
  StoichNum(25,44) = -1
  StoichNum(25,45) = -1
  StoichNum(25,49) = 1
  StoichNum(26,31) = 1
  StoichNum(26,32) = -1
  StoichNum(26,43) = -1
  StoichNum(26,44) = 1
  StoichNum(26,50) = -1
  StoichNum(27,6) = 0.3
  StoichNum(27,7) = -1
  StoichNum(27,8) = -1
  StoichNum(27,9) = -1
  StoichNum(27,10) = -1
  StoichNum(28,17) = 1
  StoichNum(28,18) = -1
  StoichNum(28,20) = -1
  StoichNum(29,1) = 1
  StoichNum(29,2) = -1
  StoichNum(29,3) = -1
  StoichNum(29,4) = -1
  StoichNum(29,5) = -2
  StoichNum(30,4) = -1
  StoichNum(30,10) = -1
  StoichNum(30,14) = -1
  StoichNum(30,19) = 1
  StoichNum(30,39) = 1
  StoichNum(30,40) = -1
  StoichNum(30,41) = -1
  StoichNum(31,3) = -1
  StoichNum(31,9) = -1
  StoichNum(31,13) = -1
  StoichNum(31,20) = -1
  StoichNum(31,26) = -1
  StoichNum(31,29) = -1
  StoichNum(31,32) = -1
  StoichNum(31,41) = -1
  StoichNum(31,49) = 1
  StoichNum(32,3) = 0.896
  StoichNum(32,9) = 0.87
  StoichNum(32,13) = 0.84
  StoichNum(32,18) = -1
  StoichNum(32,19) = 1
  StoichNum(32,20) = 0.93
  StoichNum(32,21) = 1
  StoichNum(32,23) = 1
  StoichNum(32,26) = 1
  StoichNum(32,29) = 1
  StoichNum(32,30) = -1
  StoichNum(32,32) = 2
  StoichNum(32,33) = -1
  StoichNum(32,34) = 1
  StoichNum(32,41) = 1
  StoichNum(32,42) = 1
  StoichNum(32,44) = -1
  StoichNum(32,49) = -1
  StoichNum(32,50) = 1
  StoichNum(33,11) = 1
  StoichNum(33,12) = -1
  StoichNum(33,13) = -1
  StoichNum(33,14) = -1
  StoichNum(34,1) = -1
  StoichNum(34,6) = -0.3
  StoichNum(34,7) = 1
  StoichNum(34,11) = -1
  StoichNum(34,15) = -1
  StoichNum(34,17) = -1
  StoichNum(34,21) = -1
  StoichNum(34,22) = -1
  StoichNum(34,23) = -1
  StoichNum(34,24) = -1
  StoichNum(34,25) = -1
  StoichNum(34,27) = -1
  StoichNum(34,28) = 1
  StoichNum(34,29) = 1
  StoichNum(34,30) = -1
  StoichNum(34,31) = -1
  StoichNum(34,34) = -1
  StoichNum(34,35) = -1
  StoichNum(34,36) = -1
  StoichNum(34,38) = -1
  StoichNum(34,39) = -1
  StoichNum(34,45) = 2
  StoichNum(34,46) = 2
  StoichNum(34,47) = 1
  StoichNum(34,51) = 2
  StoichNum(35,2) = -1
  StoichNum(35,3) = 0.896
  StoichNum(35,4) = 0.4
  StoichNum(35,5) = 2
  StoichNum(35,8) = -1
  StoichNum(35,12) = -1
  StoichNum(35,20) = 0.93
  StoichNum(35,21) = 1
  StoichNum(35,23) = 1
  StoichNum(35,27) = 1
  StoichNum(35,28) = -1
  StoichNum(35,29) = -1
  StoichNum(35,33) = -1
  StoichNum(35,35) = -1
  StoichNum(35,36) = 1
  StoichNum(35,37) = -2
  StoichNum(35,38) = 1
  StoichNum(35,40) = -1
  StoichNum(35,42) = 1
  StoichNum(35,48) = 2
      
END SUBROUTINE CalcStoichNum

! End of CalcStoichNum function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE cloudchem_Function

