! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-3.3.0 symbolic chemistry Kinetics PreProcessor
!       (https:/github.com/KineticPreProcessor/KPP
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian,   Villanova University, Philadelphia, PA, USA
!        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
!        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
!        H. Lin,      Harvard University, Cambridge, MA, USA
!        R. Yantosca, Harvard University, Cambridge, MA, USA
! 
! File                 : cloudchem_Monitor.F90
! Equation file        : cloudchem.kpp
! Output root filename : cloudchem
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE cloudchem_Monitor


  CHARACTER(LEN=32), PARAMETER, DIMENSION(35) :: SPC_NAMES = (/ &
     'CH3OOH                          ','ROOH                            ','ISOP1OH                         ', & ! index 1 - 3
     'ISOP1NitHP                      ','ISOPTHNit                       ','INRT                            ', & ! index 4 - 6
     'H2O2                            ','CH4                             ','HNO3                            ', & ! index 7 - 9
     'DHHPEPOX                        ','PAN                             ','IEPOX                           ', & ! index 10 - 12
     'ISOP                            ','ISOP1Nit                        ','HNO4                            ', & ! index 13 - 15
     'ISOPDHDHP                       ','ISOPDHHPNit                     ','ISOPTHHP                        ', & ! index 16 - 18
     'ISOPOOH                         ','C4CBYL                          ','CO                              ', & ! index 19 - 21
     'ISOPDiNit                       ','HCHO                            ','C4CBYLNit                       ', & ! index 22 - 24
     'O3                              ','NO3                             ','ISOP2O2                         ', & ! index 25 - 27
     'C4CBYLO2                        ','ISOP1O2                         ','RO2                             ', & ! index 28 - 30
     'NO                              ','NO2                             ','ISOP1NitO2                      ', & ! index 31 - 33
     'OH                              ','HO2                             ' /) ! index up to 35

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=32), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '       ISOP + OH --> ISOP1O2                                                                        ', & ! index 1
     '   ISOP1O2 + HO2 --> ISOPOOH                                                                        ', & ! index 2
     '    ISOP1O2 + NO --> 0.105 ISOP1Nit + 0.896 C4CBYL + 0.896 HCHO + 0.896 NO2 + 0.896 HO2             ', & ! index 3
     '   ISOP1O2 + RO2 --> 0.3 ISOP1OH + 0.7 C4CBYL + 0.4 HO2                                             ', & ! index 4
     '       2 ISOP1O2 --> 2 C4CBYL + 2 CO + 2 HO2                                                        ', & ! index 5
     '    ISOPOOH + OH --> 0.7 IEPOX + 0.3 ISOP2O2 + 0.7 OH                                               ', & ! index 6
     '         ISOP2O2 --> DHHPEPOX + OH                                                                  ', & ! index 7
     '   ISOP2O2 + HO2 --> ISOPDHDHP                                                                      ', & ! index 8
     '    ISOP2O2 + NO --> 0.13 ISOPDHHPNit + 0.87 C4CBYL + 0.87 HCHO + 0.87 NO2                          ', & ! index 9
     '   ISOP2O2 + RO2 --> 0.3 ISOPTHHP + 0.7 C4CBYL + 0.7 HCHO                                           ', & ! index 10
     '   ISOP1Nit + OH --> ISOP1NitO2                                                                     ', & ! index 11
     'ISOP1NitO2 + HO2 --> ISOP1NitHP                                                                     ', & ! index 12
     ' NO + ISOP1NitO2 --> 0.16 ISOPDiNit + 0.84 HCHO + 0.84 C4CBYLNit + 0.84 NO2                         ', & ! index 13
     'RO2 + ISOP1NitO2 --> 0.3 ISOPTHNit + 0.7 HCHO + 0.7 C4CBYLNit                                       ', & ! index 14
     '      IEPOX + OH --> C4CBYL + HCHO                                                                  ', & ! index 15
     '   DHHPEPOX + OH --> C4CBYL + HCHO + OH                                                             ', & ! index 16
     '     C4CBYL + OH --> C4CBYLO2                                                                       ', & ! index 17
     '  C4CBYLO2 + NO2 --> PAN                                                                            ', & ! index 18
     '             PAN --> RO2 + NO2                                                                      ', & ! index 19
     '   C4CBYLO2 + NO --> 1.86 CO + 1.86 HCHO + 0.07 C4CBYLNit + 0.93 NO2 + 0.93 HO2                     ', & ! index 20
     '  ISOPDiNit + OH --> HCHO + C4CBYLNit + NO2 + HO2                                                   ', & ! index 21
     '  ISOPDHDHP + OH --> C4CBYL + HCHO                                                                  ', & ! index 22
     '  C4CBYLNit + OH --> 2 CO + 2 HCHO + NO2 + HO2                                                      ', & ! index 23
     'ISOPDHHPNit + OH --> HCHO + C4CBYLNit                                                               ', & ! index 24
     '   ISOPTHHP + OH --> C4CBYL + HCHO                                                                  ', & ! index 25
     '         O3 + NO --> NO2                                                                            ', & ! index 26
     '         O3 + OH --> HO2                                                                            ', & ! index 27
     '        O3 + HO2 --> OH                                                                             ', & ! index 28
     '        NO + HO2 --> NO2 + OH                                                                       ', & ! index 29
     '        NO2 + OH --> HNO3                                                                           ' /) ! index up to 30
  CHARACTER(LEN=100), PARAMETER, DIMENSION(21) :: EQN_NAMES_1 = (/ &
     '       HNO3 + OH --> NO3                                                                            ', & ! index 31
     '        NO3 + NO --> 2 NO2                                                                          ', & ! index 32
     '       NO2 + HO2 --> HNO4                                                                           ', & ! index 33
     '       HNO4 + OH --> NO2                                                                            ', & ! index 34
     '        OH + HO2 --> INRT                                                                           ', & ! index 35
     '       HCHO + OH --> CO + HO2                                                                       ', & ! index 36
     '           2 HO2 --> H2O2                                                                           ', & ! index 37
     '         CO + OH --> HO2                                                                            ', & ! index 38
     '        CH4 + OH --> RO2                                                                            ', & ! index 39
     '       RO2 + HO2 --> ROOH                                                                           ', & ! index 40
     '        RO2 + NO --> HCHO + NO2                                                                     ', & ! index 41
     '            HNO4 --> NO2 + HO2                                                                      ', & ! index 42
     '      ISOP + NO3 --> ISOP1Nit                                                                       ', & ! index 43
     '        O3 + NO2 --> NO3                                                                            ', & ! index 44
     '              O3 --> 2 OH                                                                           ', & ! index 45
     '            H2O2 --> 2 OH                                                                           ', & ! index 46
     '          CH3OOH --> OH                                                                             ', & ! index 47
     '            HCHO --> CO + 2 HO2                                                                     ', & ! index 48
     '             NO2 --> O3 + NO                                                                        ', & ! index 49
     '             NO3 --> NO2                                                                            ', & ! index 50
     '         ISOPOOH --> HCHO + 2 OH                                                                    ' /) ! index up to 51
  CHARACTER(LEN=100), PARAMETER, DIMENSION(51) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1 /)

  CHARACTER(LEN=32), DIMENSION(1) :: FAM_NAMES
! Begin inlined code from F90_DATA

! End inlined code from F90_DATA


END MODULE cloudchem_Monitor
