! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-3.3.0 symbolic chemistry Kinetics PreProcessor
!       (https:/github.com/KineticPreProcessor/KPP
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian,   Villanova University, Philadelphia, PA, USA
!        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
!        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
!        H. Lin,      Harvard University, Cambridge, MA, USA
!        R. Yantosca, Harvard University, Cambridge, MA, USA
! 
! File                 : cloudchem_Parameters.F90
! Equation file        : cloudchem.kpp
! Output root filename : cloudchem
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE cloudchem_Parameters

  USE cloudchem_Precision
  PUBLIC
  SAVE


! NSPEC - Number of chemical species
  INTEGER, PARAMETER :: NSPEC = 35 
! NVAR - Number of Variable species
  INTEGER, PARAMETER :: NVAR = 35 
! NFAM - Number of Prod/Loss Families
  INTEGER, PARAMETER :: NFAM = 1 
! NVARACT - Number of Active species
  INTEGER, PARAMETER :: NVARACT = 30 
! NFIX - Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 1 
! NREACT - Number of reactions
  INTEGER, PARAMETER :: NREACT = 51 
! NVARST - Starting of variables in conc. vect.
  INTEGER, PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER, PARAMETER :: NFIXST = 36 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 213 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 236 
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER, PARAMETER :: CNVAR = 36 
! NLOOKAT - Number of species to look at
  INTEGER, PARAMETER :: NLOOKAT = 0 
! NMONITOR - Number of species to monitor
  INTEGER, PARAMETER :: NMONITOR = 0 
! NMASS - Number of atoms to check mass balance
  INTEGER, PARAMETER :: NMASS = 1 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)

  INTEGER, PARAMETER :: ind_CH3OOH = 1 
  INTEGER, PARAMETER :: ind_ROOH = 2 
  INTEGER, PARAMETER :: ind_ISOP1OH = 3 
  INTEGER, PARAMETER :: ind_ISOP1NitHP = 4 
  INTEGER, PARAMETER :: ind_ISOPTHNit = 5 
  INTEGER, PARAMETER :: ind_INRT = 6 
  INTEGER, PARAMETER :: ind_H2O2 = 7 
  INTEGER, PARAMETER :: ind_CH4 = 8 
  INTEGER, PARAMETER :: ind_HNO3 = 9 
  INTEGER, PARAMETER :: ind_DHHPEPOX = 10 
  INTEGER, PARAMETER :: ind_PAN = 11 
  INTEGER, PARAMETER :: ind_IEPOX = 12 
  INTEGER, PARAMETER :: ind_ISOP = 13 
  INTEGER, PARAMETER :: ind_ISOP1Nit = 14 
  INTEGER, PARAMETER :: ind_HNO4 = 15 
  INTEGER, PARAMETER :: ind_ISOPDHDHP = 16 
  INTEGER, PARAMETER :: ind_ISOPDHHPNit = 17 
  INTEGER, PARAMETER :: ind_ISOPTHHP = 18 
  INTEGER, PARAMETER :: ind_ISOPOOH = 19 
  INTEGER, PARAMETER :: ind_C4CBYL = 20 
  INTEGER, PARAMETER :: ind_CO = 21 
  INTEGER, PARAMETER :: ind_ISOPDiNit = 22 
  INTEGER, PARAMETER :: ind_HCHO = 23 
  INTEGER, PARAMETER :: ind_C4CBYLNit = 24 
  INTEGER, PARAMETER :: ind_O3 = 25 
  INTEGER, PARAMETER :: ind_NO3 = 26 
  INTEGER, PARAMETER :: ind_ISOP2O2 = 27 
  INTEGER, PARAMETER :: ind_C4CBYLO2 = 28 
  INTEGER, PARAMETER :: ind_ISOP1O2 = 29 
  INTEGER, PARAMETER :: ind_RO2 = 30 
  INTEGER, PARAMETER :: ind_NO = 31 
  INTEGER, PARAMETER :: ind_NO2 = 32 
  INTEGER, PARAMETER :: ind_ISOP1NitO2 = 33 
  INTEGER, PARAMETER :: ind_OH = 34 
  INTEGER, PARAMETER :: ind_HO2 = 35 

! Index declaration for fixed species in C
!   C(ind_spc)


! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)


END MODULE cloudchem_Parameters

